---
- name: Reset altdomainnames variable
  set_fact:
    altdomainnames: ""

- name: Prepare alt domain names
  set_fact:
    altdomainnames: "-d {{ crt.altnames | join(' -d ') }}"
  when: crt.altnames is defined

- name: "Register domain {{ crt.name }} via certbot"
  command: >
    certbot certonly
      --webroot
      -w /var/www/letsencrypt/
      -d {{ crt.name }} {{ altdomainnames|default('') }}
      --non-interactive
      --agree-tos
      -m {{ crt.mail }}
  args:
    creates: "/etc/letsencrypt/live/{{ crt.name }}/fullchain.pem"
  register: letsencrypt_output
