---
- name: Check if nginx is installed
  package:
    name: nginx
    state: present
  check_mode: true
  changed_when: false
  register: nginx_check

- name: Fail if nginx is not installed
  fail:
    msg: "Nginx installation not found. This role requires Nginx to run"
  when: nginx_check is not succeeded

- name: Install letsencrypt
  apt:
    name: letsencrypt

- name: Create needed dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /var/www/letsencrypt/
    - /etc/letsencrypt/renewal-hooks/post

- name: Deploy restart hook if nginx is installed
  copy:
    src: etc/letsencrypt/renewal-hooks/post/nginx.sh
    dest: /etc/letsencrypt/renewal-hooks/post/nginx.sh
    mode: 0755

- name: Deploy letsencrypt certs
  include_tasks: deploy_letsencrypt.yml
  loop_control:
    loop_var: crt
    label: "{{ crt.name }}"
  with_items: "{{ letsencrypt_cert_list }}"
  when: crt.state|default('present') == 'present'

- name: Undeploy certs which should be undeployed
  include_tasks: undeploy_letsencrypt.yml
  loop_control:
    loop_var: crt
  with_items: "{{ letsencrypt_cert_list }}"
  when: crt.state|default('present') == 'absent'

- name: Generate dhparam if it doesn't exist yet
  command: "openssl dhparam -out {{ letsencrypt_dhparam }} 2048"
  args:
    creates: "{{ letsencrypt_dhparam }}"
